substitutions:
  device: esp-pixel-clock-ru
  name: ESPHome Pixel Clock
  project_name: "ajs.Pixel_Clock"
  project_version: "1.1.5"
  update_interval: 60s
  comment: "Ulanzi Pixel Clock | EHMTXv2"
  weekdays: "ВСПНВТСРЧТПТСБ"
  date_to: "ВС ПН ВТ СР ЧТ ПТ СБ Янв Фев Мар Апр Май Июн Июл Авг Сен Окт Ноя Дек"

dashboard_import:
  package_import_url: github://andrewjswan/pixel-clock/pixel-clock.yaml@main

packages:
  common: !include packages/common.yaml
  pixel: !include packages/pixel_clock.yaml
  # sun: !include packages/pixel_clock_sun.yaml
  timezone: !include packages/pixel_timezone.yaml
