substitutions:
  reboot_timeout: 0s

esphome:
  name: ${device}
  # name_add_mac_suffix: true
  comment: $comment
  build_path: ./.build/$device
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32dev

api:
  reboot_timeout: ${reboot_timeout}

# Over The Air Update
ota:
  - platform: esphome
    on_error:
      then:
        - logger.log:
            format: "OTA Update error %d"
            args: ["x"]
            level: "ERROR"
            tag: "ota"
    on_end:
      then:
        - logger.log:
            format: "OTA Update has completed successfully"
            level: "WARN"
            tag: "ota"

logger:
  level: INFO

mdns:
  disabled: false

web_server:
  port: 80
  log: false
  version: 3

wifi:
  ap: {}

captive_portal:

improv_serial:

sensor:
  - platform: uptime
    name: ${name} Uptime
    entity_category: diagnostic

  - platform: wifi_signal
    name: ${name} WiFi Signal
    entity_category: diagnostic
    icon: mdi:signal

  - platform: internal_temperature
    name: ${name} Device Temperature
    entity_category: diagnostic
    icon: mdi:coolant-temperature
    device_class: temperature
    disabled_by_default: true

button:
  - platform: restart
    name: ${name} Restart
    id: Restart
    entity_category: diagnostic
    icon: mdi:restart

  - platform: factory_reset
    name: ${name} Restart with Factory Default Settings
    id: Reset
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: ${name} ESPHome Version
    hide_timestamp: true
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: "${name} IP Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:ip
    ssid:
      name: "${name} Connected SSID"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:access-point-network
    mac_address:
      name: "${name} Mac Address"
      disabled_by_default: true
      entity_category: diagnostic
      icon: mdi:console-network
